version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    groups:
      kotlin-toolchain:
        patterns:
          - "org.jetbrains.kotlin*"
      kotlinx-runtime:
        patterns:
          - "org.jetbrains.kotlinx*"
      logging:
        patterns:
          - "org.slf4j*"
          - "ch.qos.logback*"
          - "io.github.microutils*"
      junit:
        patterns:
          - "org.junit*"
      mockito:
        patterns:
          - "org.mockito*"
      assertions:
        patterns:
          - "org.assertj*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
