name: Supply Chain - OSV

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  osv-pr:
    if: github.event_name == 'pull_request'
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.8
    with:
      checkout-submodules: true
      scan-args: |-
        -r
        ./

  osv-scheduled:
    if: github.event_name != 'pull_request'
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.5.0
    with:
      checkout-submodules: true
      fail-on-vuln: false
      scan-args: |-
        -r
        ./
